default_language_version:
  python: python3.11
exclude: migrations|storage
repos:
  - repo: https://github.com/python-poetry/poetry
    rev: "1.8"
    hooks:
      - id: poetry-check
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-xml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
  # - repo: local
  # hooks:
  # - id: pytest
  # name: pytest
  # language: system
  # Тоже самое что и  "bash -c 'cd backend && pytest --reuse-db .'", но работает на всех OC
  # entry: poetry run python -c "import os, subprocess; os.chdir('backend'); subprocess.check_call(['pytest', '.'])"
  # pass_filenames: false
  # stages: [push]
